/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksDailyRunRouteImport } from './routes/api/public/hooks/daily-run'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDailyRunRoute = ApiPublicHooksDailyRunRouteImport.update({
  id: '/api/public/hooks/daily-run',
  path: '/api/public/hooks/daily-run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/api/public/hooks/daily-run': typeof ApiPublicHooksDailyRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/generate'
    | '/history'
    | '/login'
    | '/logs'
    | '/schedule'
    | '/settings'
    | '/api/public/hooks/daily-run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/generate'
    | '/history'
    | '/login'
    | '/logs'
    | '/schedule'
    | '/settings'
    | '/api/public/hooks/daily-run'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/generate'
    | '/history'
    | '/login'
    | '/logs'
    | '/schedule'
    | '/settings'
    | '/api/public/hooks/daily-run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  GenerateRoute: typeof GenerateRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicHooksDailyRunRoute: typeof ApiPublicHooksDailyRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-run': {
      id: '/api/public/hooks/daily-run'
      path: '/api/public/hooks/daily-run'
      fullPath: '/api/public/hooks/daily-run'
      preLoaderRoute: typeof ApiPublicHooksDailyRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  GenerateRoute: GenerateRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicHooksDailyRunRoute: ApiPublicHooksDailyRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
